const newOrders: Array<IPayment> = [
  // const newOrders = [
    {
        // ID: 1,
        // OrderNumber: 35703,
        // OrderDate: "2017/04/10",
        // DeliveryDate: "2017/04/13 9:00",
        // SaleAmount: 11800,
        // Terms: "15 Days",
        // CustomerStoreCity: "Los Angeles, CA",
        // Employee: "Harv Mudd",
    
        tscode: 1,
        tok: "1_tok",
        tnumber: 1,
        mname: "1_mname",
        mid: "1_mid",
        spay: 1,
        trno: "1",
        reg_date: "2020-03-23T00:16:59.718Z",
        pay_dtm: "2020-03-23T00:16:59.718Z",
        content: "1_content",
        bpay: 1,
        qpay: 1,
        brefund: 1,
        qrefund: 1,
        accea: 1,
        qaccea: 1,
        req_day: "1_req_day",
        req_qday: "1_req_qday",
        endday: "1_endday",
        qendday: "1_qendday",
        msg2: "1_messag2"
    },
    {
        tscode: 2,
        tok: "2_tok",
        tnumber: 2,
        mname: "2_mname",
        mid: "2_mid",
        spay: 2,
        trno: "2",
        reg_date: "2020-03-23T00:16:59.718Z",
        pay_dtm: "2020-03-23T00:16:59.718Z",
        content: "2_content",
        bpay: 2,
        qpay: 2,
        brefund: 2,
        qrefund: 2,
        accea: 2,
        qaccea: 2,
        req_day: "2_req_day",
        req_qday: "2_req_qday",
        endday: "2_endday",
        qendday: "2_qendday",
        msg2: "2_messag2"
    },
    {
        tscode: 2,
        tok: "2_tok",
        tnumber: 2,
        mname: "2_mname",
        mid: "2_mid",
        spay: 2,
        trno: "2",
        reg_date: "2020-03-23T00:16:59.718Z",
        pay_dtm: "2020-03-23T00:16:59.718Z",
        content: "2_content",
        bpay: 2,
        qpay: 2,
        brefund: 2,
        qrefund: 2,
        accea: 2,
        qaccea: 2,
        req_day: "2_req_day",
        req_qday: "2_req_qday",
        endday: "2_endday",
        qendday: "2_qendday",
        msg2: "2_messag2"
    },
    {
        tscode: 2,
        tok: "2_tok",
        tnumber: 2,
        mname: "2_mname",
        mid: "2_mid",
        spay: 2,
        trno: "2",
        reg_date: "2020-03-23T00:16:59.718Z",
        pay_dtm: "2020-03-23T00:16:59.718Z",
        content: "2_content",
        bpay: 2,
        qpay: 2,
        brefund: 2,
        qrefund: 2,
        accea: 2,
        qaccea: 2,
        req_day: "2_req_day",
        req_qday: "2_req_qday",
        endday: "2_endday",
        qendday: "2_qendday",
        msg2: "2_messag2"
    },
    {
        tscode: 2,
        tok: "2_tok",
        tnumber: 2,
        mname: "2_mname",
        mid: "2_mid",
        spay: 2,
        trno: "2",
        reg_date: "2020-03-23T00:16:59.718Z",
        pay_dtm: "2020-03-23T00:16:59.718Z",
        content: "2_content",
        bpay: 2,
        qpay: 2,
        brefund: 2,
        qrefund: 2,
        accea: 2,
        qaccea: 2,
        req_day: "2_req_day",
        req_qday: "2_req_qday",
        endday: "2_endday",
        qendday: "2_qendday",
        msg2: "2_messag2"
    }
];
    
export default {
    getNewOrders() {
        return newOrders;
    }
  };
        